//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class activeListingPhoto
    {
        public int ActiveListingPhotoId { get; set; }
        public string ActiveListingId { get; set; }
        public string PhotoURL { get; set; }
        public string PhotoOrder { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string IsVideo { get; set; }
    }
}
