//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActiveListing
    {
        public string ActiveListingId { get; set; }
        public string Age { get; set; }
        public string Color { get; set; }
        public string Dam { get; set; }
        public string Sire { get; set; }
        public string DamSire { get; set; }
        public string Description { get; set; }
        public string Gender { get; set; }
        public string HorseName { get; set; }
        public Nullable<bool> InFoal { get; set; }
        public Nullable<decimal> Lte { get; set; }
        public Nullable<System.DateTime> OriginalDateListed { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PurchaseListingType { get; set; }
        public string RanchPhoto { get; set; }
        public string SellerId { get; set; }
        public string HorseType { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public string InFoalTo { get; set; }
        public Nullable<bool> CallForPrice { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<bool> isSireRegistered { get; set; }
        public Nullable<bool> isDamSireRegistered { get; set; }
    }
}
