//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActiveListingPhoto
    {
        public long ActiveListingPhotoId { get; set; }
        public string ActiveListingId { get; set; }
        public string PhotoURL { get; set; }
        public Nullable<int> PhotoOrder { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsVideo { get; set; }
    }
}
